Repository Ekumen-OS/beluga, pull requests merged in 2023-05, with the labels that each got.

#191 Configure codecov
  .codecov.yml
  .github/workflows/ci_pipeline.yml
  README.md
Labels: enhancement, infra

#188 Rework occupancy grids
  beluga/include/beluga/algorithm/raycasting.hpp
  beluga/include/beluga/sensor/beam_model.hpp
  beluga/include/beluga/sensor/data/dense_grid.hpp
  beluga/include/beluga/sensor/data/linear_grid.hpp
  beluga/include/beluga/sensor/data/occupancy_grid.hpp
  beluga/include/beluga/sensor/data/regular_grid.hpp
  beluga/include/beluga/sensor/data/value_grid.hpp
  beluga/include/beluga/sensor/likelihood_field_model.hpp
  beluga/test/beluga/CMakeLists.txt
  beluga/test/beluga/algorithm/test_raycasting.cpp
  beluga/test/beluga/include/beluga/test/static_occupancy_grid.hpp
  beluga/test/beluga/sensor/data/test_dense_grid.cpp
  beluga/test/beluga/sensor/data/test_linear_grid.cpp
  beluga/test/beluga/sensor/data/test_occupancy_grid.cpp
  beluga/test/beluga/sensor/data/test_regular_grid.cpp
  beluga/test/beluga/sensor/test_beam_model.cpp
  beluga/test/beluga/sensor/test_likelihood_field_model.cpp
  beluga/test/benchmark/CMakeLists.txt
  beluga/test/benchmark/benchmark_raycasting.cpp
  beluga_amcl/include/beluga_amcl/occupancy_grid.hpp
Labels: enhancement, cpp

#192 Add missing documentation links
  GETTING_STARTED.md
  beluga/README.md
  beluga/include/beluga/algorithm/estimation.hpp
  beluga/include/beluga/sensor.hpp
Labels: documentation, enhancement

#193 Add performance report for latest version with minor fixes to scripts
  beluga_amcl/README.md
  beluga_benchmark/CMakeLists.txt
  beluga_benchmark/beluga_benchmark/compare_results.py
  beluga_benchmark/docs/reports/2023-05-20/REPORT.md
  beluga_benchmark/docs/reports/2023-05-20/beam_par_beluga_vs_amcl.png
  beluga_benchmark/docs/reports/2023-05-20/beam_params.yaml
  beluga_benchmark/docs/reports/2023-05-20/beam_params_par.yaml
  beluga_benchmark/docs/reports/2023-05-20/beam_seq_beluga_vs_amcl.png
  beluga_benchmark/docs/reports/2023-05-20/likelihood_par_beluga_vs_amcl.png
  beluga_benchmark/docs/reports/2023-05-20/likelihood_params.yaml
  beluga_benchmark/docs/reports/2023-05-20/likelihood_params_par.yaml
  beluga_benchmark/docs/reports/2023-05-20/likelihood_seq_beluga_vs_amcl.png
  beluga_benchmark/scripts/benchmarking/parameterized_run
Labels: documentation, enhancement

#195 Remove shared_mutexes to address concurrency performance
  beluga/include/beluga/motion/differential_drive_model.hpp
  beluga/include/beluga/motion/omnidirectional_drive_model.hpp
  beluga/include/beluga/sensor/beam_model.hpp
  beluga/include/beluga/sensor/likelihood_field_model.hpp
  beluga_benchmark/beluga_benchmark/compare_results.py
  beluga_benchmark/docs/BENCHMARKING.md
Labels: enhancement, cpp

#189 Add support for map updates in laser localization filters
  beluga/include/beluga/localization.hpp
  beluga/include/beluga/sensor.hpp
  beluga/include/beluga/sensor/beam_model.hpp
  beluga/include/beluga/sensor/likelihood_field_model.hpp
  beluga/test/beluga/sensor/test_beam_model.cpp
  beluga/test/beluga/sensor/test_likelihood_field_model.cpp
  beluga_amcl/include/beluga_amcl/private/amcl_node.hpp
  beluga_amcl/src/amcl_node.cpp
  beluga_system_tests/test/test_system.cpp
Labels: enhancement, cpp

#194 Add tests for the AMCL node
  .codecov.yml
  beluga_amcl/src/amcl_node.cpp
  beluga_amcl/test/CMakeLists.txt
  beluga_amcl/test/test_amcl_node.cpp
Labels: enhancement, cpp

#196 Add AMCL parameter reference page
  beluga_amcl/README.md
  beluga_amcl/docs/PARAMETERS.md
Labels: documentation, enhancement

#197 Re-organize infrastructure scripts
  .codecov.yml
  .github/workflows/ci_pipeline.yml
  .gitignore
  GETTING_STARTED.md
  beluga/.gitignore
  beluga/CMakeLists.txt
  beluga/docs/CMakeLists.txt
  beluga/docs/Doxyfile
  beluga/docs/generate_docs.sh
  beluga/run-clang-tidy.sh
  beluga_system_tests/run-clang-tidy.sh
  docker/images/humble/Dockerfile
  docker/images/rolling/Dockerfile
  docker/run.sh
  tools/README.md
  tools/build-and-test.sh
  tools/run-clang-tidy.sh
Labels: enhancement, infra

#200 Optimize beam sensor model runtime performance
  beluga/include/beluga/algorithm/raycasting.hpp
  beluga/include/beluga/sensor/beam_model.hpp
  beluga/include/beluga/sensor/data/regular_grid.hpp
  beluga_amcl/src/amcl_node.cpp
Labels: enhancement, cpp

#203 Change default threading mode to the less cpu-consuming one
  beluga_amcl/src/amcl_node.cpp
Labels: enhancement

#204 Install doxygen-awesome
  beluga/docs/CMakeLists.txt
  beluga/docs/Doxyfile
  beluga/docs/doxygen_extra.css
Labels: documentation, enhancement

#199 Optimize likelihood field model runtime performance
  beluga/include/beluga/sensor/data/dense_grid.hpp
  beluga/include/beluga/sensor/data/regular_grid.hpp
  beluga/include/beluga/sensor/likelihood_field_model.hpp
  beluga/test/beluga/sensor/test_likelihood_field_model.cpp
  beluga_benchmark/beluga_benchmark/compare_results.py
Labels: enhancement, cpp

#205 Disable branch and function coverage
  .lcovrc
  beluga_amcl/src/amcl_node.cpp
  tools/build-and-test.sh
Labels: enhancement, infra

#201 Extend raycast microbenchmarks
  beluga/test/beluga/algorithm/test_raycasting.cpp
  beluga/test/beluga/include/beluga/test/raycasting.hpp
  beluga/test/benchmark/benchmark_raycasting.cpp
Labels: enhancement, cpp
