Repository Ekumen-OS/beluga, pull requests merged in 2023-06, with the labels that each got.

#212 Fix map to odom transform calculation
  beluga_amcl/src/amcl_node.cpp
  beluga_amcl/test/test_amcl_node.cpp
Labels: bug

#214 Fix typo in pull request template
  .github/pull_request_template.md
Labels: bug, documentation

#217 Add ROS Noetic CI infrastructure
  .github/workflows/ci_pipeline.yml
  .github/workflows/docker_ci_pipeline.yml
  beluga/CMakeLists.txt
  beluga/test/beluga/type_traits/test_strongly_typed_numeric.cpp
  docker/images/noetic/Dockerfile
  tools/build-and-test.sh
  tools/run-clang-tidy.sh
Labels: enhancement, ros, infra

#220 Fix flaky transform test
  beluga_amcl/test/test_amcl_node.cpp
Labels: bug, cpp

#228 List documentation deps in package.xml
  .github/workflows/ci_pipeline.yml
  beluga/docs/CMakeLists.txt
  beluga/package.xml
  docker/images/humble/Dockerfile
  docker/images/noetic/Dockerfile
  docker/images/rolling/Dockerfile
Labels: enhancement, infra

#229 Add installation guide
  GETTING_STARTED.md
  INSTALLING.md
  README.md
Labels: documentation, enhancement

#234 Avoid building docs by default
  INSTALLING.md
  beluga/CMakeLists.txt
  tools/build-and-test.sh
Labels: enhancement, infra

#231 Speed up docker builds in CI
  .github/workflows/ci_pipeline.yml
  .github/workflows/docker_ci_pipeline.yml
  docker/images/humble/Dockerfile
  docker/images/noetic/Dockerfile
  docker/images/rolling/Dockerfile
Labels: enhancement, infra
