Repository Ekumen-OS/beluga, pull requests merged in 2023-07, with the labels that each got.

#233 Refactor resampling policies into filter update control
  beluga/docs/README.md
  beluga/include/beluga/algorithm/particle_filter.hpp
  beluga/include/beluga/beluga.hpp
  beluga/include/beluga/localization.hpp
  beluga/include/beluga/motion.hpp
  beluga/include/beluga/motion/differential_drive_model.hpp
  beluga/include/beluga/motion/omnidirectional_drive_model.hpp
  beluga/include/beluga/motion/stationary_model.hpp
  beluga/include/beluga/resampling_policies.hpp
  beluga/include/beluga/resampling_policies/resample_on_motion_policy.hpp
  beluga/include/beluga/resampling_policies/resampling_policies_poller.hpp
  beluga/test/beluga/CMakeLists.txt
  beluga/test/beluga/algorithm/test_particle_filter.cpp
  beluga/test/beluga/motion/test_differential_drive_model.cpp
  beluga/test/beluga/motion/test_omnidirectional_drive_model.cpp
  beluga/test/beluga/resampling_policies/test_resample_on_motion_policy.cpp
  beluga/test/beluga/resampling_policies/test_resampling_policies_poller.cpp
  beluga_amcl/include/beluga_amcl/filter_update_control/filter_update_control_mixin.hpp
  beluga_amcl/include/beluga_amcl/filter_update_control/resample_interval_policy.hpp
  beluga_amcl/include/beluga_amcl/filter_update_control/selective_resampling_policy.hpp
  beluga_amcl/include/beluga_amcl/filter_update_control/update_filter_when_moving_policy.hpp
  beluga_amcl/include/beluga_amcl/particle_filtering.hpp
  beluga_amcl/include/beluga_amcl/private/amcl_node.hpp
  beluga_amcl/include/beluga_amcl/private/amcl_nodelet.hpp
  beluga_amcl/src/amcl_node.cpp
  beluga_amcl/src/amcl_nodelet.cpp
  beluga_amcl/test/cmake/ament.cmake
  beluga_amcl/test/cmake/catkin.cmake
  beluga_amcl/test/filter_update_control/test_filter_update_control_mixin.cpp
  beluga_amcl/test/filter_update_control/test_resample_interval_policy.cpp
  beluga_amcl/test/filter_update_control/test_selective_resampling_policy.cpp
  beluga_amcl/test/filter_update_control/test_update_filter_when_moving_policy.cpp
  beluga_system_tests/test/test_system.cpp
Labels: enhancement, cpp

#236 Remove uncrustify and cpplint from pre-commit hooks
  .clang-tidy
  .pre-commit-config.yaml
  beluga_amcl/CMakeLists.txt
  beluga_amcl/include/beluga_amcl/amcl_node_utils.hpp
  beluga_amcl/include/beluga_amcl/filter_update_control/filter_update_control_mixin.hpp
  beluga_amcl/include/beluga_amcl/filter_update_control/resample_interval_policy.hpp
  beluga_amcl/include/beluga_amcl/filter_update_control/selective_resampling_policy.hpp
  beluga_amcl/include/beluga_amcl/filter_update_control/update_filter_when_moving_policy.hpp
  beluga_amcl/include/beluga_amcl/occupancy_grid.hpp
  beluga_amcl/include/beluga_amcl/particle_filtering.hpp
  beluga_amcl/include/beluga_amcl/private/amcl_node.hpp
  beluga_amcl/include/beluga_amcl/private/amcl_nodelet.hpp
  beluga_amcl/include/beluga_amcl/private/execution_policy.hpp
  beluga_amcl/include/beluga_amcl/ros_interfaces.hpp
  beluga_amcl/include/beluga_amcl/tf2_sophus.hpp
  beluga_amcl/package.xml
  beluga_amcl/src/amcl_node.cpp
  beluga_amcl/src/amcl_node_utils.cpp
  beluga_amcl/src/amcl_nodelet.cpp
  beluga_amcl/src/particle_filtering.cpp
  beluga_amcl/test/cmake/ament.cmake
  beluga_amcl/test/cmake/catkin.cmake
  beluga_amcl/test/filter_update_control/test_filter_update_control_mixin.cpp
  beluga_amcl/test/filter_update_control/test_resample_interval_policy.cpp
  beluga_amcl/test/filter_update_control/test_selective_resampling_policy.cpp
  beluga_amcl/test/filter_update_control/test_update_filter_when_moving_policy.cpp
  beluga_amcl/test/test_amcl_node.cpp
  beluga_amcl/test/test_amcl_node_utils.cpp
  beluga_amcl/test/test_amcl_nodelet.cpp
  tools/run-clang-tidy.sh
Labels: enhancement, infra

#237 Remove ament_flake8 from pre-commit hooks
  .flake8
  .pre-commit-config.yaml
  beluga_amcl/package.xml
  docker/images/noetic/Dockerfile
Labels: enhancement, infra

#240 Replace ament_copyright with local script
  .github/workflows/ci_pipeline.yml
  .pre-commit-config.yaml
  GETTING_STARTED.md
  README.md
  beluga_amcl/package.xml
  docker/images/noetic/Dockerfile
  tools/check_copyright.py
Labels: enhancement, infra, python

#242 Rename motion models in Beluga AMCL for ROS 1
  beluga_amcl/docs/PARAMETERS.md
  beluga_amcl/src/amcl_nodelet.cpp
  beluga_example/params/default.ros.yaml
Labels: enhancement, ros

#241 Reduce simulated odometry noise
  beluga_example/models/turtlebot.model.yaml
Labels: bug

#239 Update video in README.md
  README.md
Labels: documentation, enhancement

#243 Add cmake-format to pre-commit hooks
  .cmake-format
  .pre-commit-config.yaml
  beluga/CMakeLists.txt
  beluga/docs/CMakeLists.txt
  beluga/test/CMakeLists.txt
  beluga/test/beluga/CMakeLists.txt
  beluga/test/benchmark/CMakeLists.txt
  beluga_amcl/CMakeLists.txt
  beluga_amcl/cmake/ament.cmake
  beluga_amcl/cmake/catkin.cmake
  beluga_amcl/cmake/lib/nodelets.cmake
  beluga_amcl/package.xml
  beluga_amcl/test/CMakeLists.txt
  beluga_amcl/test/cmake/ament.cmake
  beluga_amcl/test/cmake/catkin.cmake
  beluga_benchmark/CMakeLists.txt
  beluga_example/CMakeLists.txt
  beluga_example/cmake/ament.cmake
  beluga_example/cmake/catkin.cmake
  beluga_example/package.xml
  beluga_system_tests/CMakeLists.txt
  beluga_system_tests/test/CMakeLists.txt
Labels: enhancement, infra

#244 Change default AMCL params
  beluga_amcl/config/Amcl.cfg
  beluga_amcl/src/amcl_node.cpp
  beluga_amcl/test/test_amcl_node.cpp
  beluga_amcl/test/test_amcl_nodelet.cpp
Labels: enhancement, ros

#247 Add ROS 2 Iron CI infrastructure
  .github/workflows/ci_pipeline.yml
  .github/workflows/docker_ci_pipeline.yml
  .github/workflows/weekly_pipeline.yml
  GETTING_STARTED.md
  docker/files/iron.repos
  docker/images/iron/Dockerfile
Labels: enhancement, infra
