Repository Ekumen-OS/beluga, pull requests merged in 2024-05, with the labels that each got.

#352 Clang tidy doesn't sort includes
  .clang-tidy
Labels: bug, enhancement, infra

#353 Allow coverage to drop by 1%
  .codecov.yml
Labels: bug, infra

#347 Add NDT AMCL node and tests.
  beluga_amcl/cmake/ament.cmake
  beluga_amcl/include/beluga_amcl/ndt_amcl_node.hpp
  beluga_amcl/include/beluga_amcl/ros2_common.hpp
  beluga_amcl/src/amcl_node.cpp
  beluga_amcl/src/ndt_amcl_node.cpp
  beluga_amcl/test/cmake/ament.cmake
  beluga_amcl/test/test_amcl_node.cpp
  beluga_amcl/test/test_data/turtlebot3_world.hdf5
  beluga_amcl/test/test_ndt_amcl_node.cpp
  beluga_amcl/test/test_utils/node_testing.hpp
Labels: enhancement, cpp

#363 Add conversion script from PLY to NDT
  beluga_ros/package.xml
  beluga_ros/setup.cfg
  beluga_ros/src/beluga_ros/__init__.py
  beluga_ros/src/beluga_ros/ply_to_ndt.py
Labels: python

#371 Ensure we exercise random state generation every time
  beluga/test/beluga/algorithm/test_amcl_core.cpp
Labels: bug, cpp

#362 Add 1D particle filter tutorial code
  beluga/include/beluga/algorithm/estimation.hpp
  beluga/test/beluga/algorithm/test_estimation.cpp
  beluga_tutorial/CMakeLists.txt
  beluga_tutorial/package.xml
  beluga_tutorial/params/tutorial.yaml
  beluga_tutorial/src/main.cpp
Labels: cpp

#384 Rewrite `make_from_state` as a function object
  beluga/include/beluga/type_traits/particle_traits.hpp
  beluga/test/beluga/views/test_sample.cpp
Labels: bug, cpp

#386 Support 32-bit hashes
  beluga/include/beluga/algorithm/spatial_hash.hpp
Labels: cpp

#383 Reduce duplication when using `yaml-cpp`
  beluga_tutorial/package.xml
  beluga_tutorial/src/main.cpp
Labels: cpp

#390 Add ROS 2 condition for `yaml_cpp_vendor` package
  .github/workflows/docker_ci_pipeline.yml
  beluga_tutorial/package.xml
Labels: bug, infra

#392 Add cast from `hsize_t` to `size_t`
  beluga/include/beluga/sensor/ndt_sensor_model.hpp
Labels: bug, cpp

#393 Adapt beluga_tutorial code to key concepts
  beluga_tutorial/src/main.cpp
Labels: cpp

#394 Update binary install instructions
  docs/_images/jazzy_jalisco_logo.png
  docs/_images/rolling_ridley_logo.png
  docs/getting-started/installation.md
  docs/index.md
Labels: documentation
